---
title: "Model Building"
author: "Venkat Battepati"
date: '2022-04-03'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(psych) # Contains the winsor function and other helpful statistical tools
library(tidyverse) # Remember from last homework that dplyr is included in tidyverse
library(gridExtra)
library(corrplot)
library(patchwork)
library(grid)
library(caTools)
library(factoextra)
library(FactoMineR)
library(mice) # Multiple imputation - may not use
library(xgboost)
library(klaR) # kmodes function 
```

Reading datasets

```{r}
control_file="https://raw.githubusercontent.com/braden2447/BME-580-Project/main/Sepsis_control_data.csv"
positive_file = "https://raw.githubusercontent.com/braden2447/BME-580-Project/main/Sepsis_positive_data.csv"

control <- read.csv(url(control_file))
positive <- read.csv(url(positive_file))
positive$sepsis_group <- NULL
control$sepsis_group <- NULL
control$sepsis = 0
positive$sepsis = 1
df = rbind(control,positive)
head(df)
```


```{r}
df$capPH = NULL
```

Data division to test and train

```{r}
split = sample.split(control$sepsis, SplitRatio=.8)

train <- subset(control, split==TRUE) 
test <- subset(control,split ==FALSE)

spliti = sample.split(positive$sepsis, SplitRatio=.8)

traini <- subset(positive, split==TRUE) 
testi <- subset(positive, split ==FALSE)

```

Model building

```{r}
logModel = glm(sepsis ~., family = binomial, data = train)
summary(logModel)
```



```{r}
log.fit = predict(logModel, newdata = test, type = 'sepsis')
```

